# include<stdio.h>

int main(void)
{
 int num,direct,i,j,k,n=0;
 //scan num and direction
 scanf("%d",&num);
 scanf("%d",&direct);
 int a[num][num];
 for(i=0;i<num;i++)
    for(j=0;j<num;j++)
        a[i][j]=0;
 if(direct==1)
 {
     for(i=0,j=0,k=1;k<=num*num;k++)
     {
         if(n==0)
         {
             if(j<num&&a[i][j]==0)
             {
                 a[i][j]=k;
                 j++;
             }
             else
            {
                i++;
                j--;
                k--;
                n++;
            }
         }
         else if(n==1)
         {
             if(i<num&&a[i][j]==0)
             {
                 a[i][j]=k;
                 i++;
             }
             else
             {
                 j--;
                 i--;
                 k--;
                 n++;
             }
         }
         else if(n==2)
         {
             if(j>=0&&a[i][j]==0)
             {
                 a[i][j]=k;
                 j--;
             }
             else
             {
                 i--;
                 j++;
                 k--;
                 n++;
             }
         }
         else if(n==3)
         {
             if(i>=0&&a[i][j]==0)
             {
                 a[i][j]=k;
                 i--;
             }
             else
             {
                 i++;
                 j++;
                 k--;
                 n=0;
             }
         }
     }
 }
 else
 {
     for(i=0,j=0,k=1;k<=num*num;k++)
     {
         if(n==0)
         {
             if(i<num&&a[i][j]==0)
             {
                 a[i][j]=k;
                 i++;
             }
             else
             {
                 j++;
                 i--;
                 k--;
                 n++;
             }
         }
         else if(n==1)
         {
             if(j<num&&a[i][j]==0)
             {
                 a[i][j]=k;
                 j++;
             }
             else
            {
                i--;
                j--;
                k--;
                n++;
            }
         }
         else if(n==2)
         {
             if(i>=0&&a[i][j]==0)
             {
                 a[i][j]=k;
                 i--;
             }
             else
             {
                 i++;
                 j--;
                 k--;
                 n++;
             }
         }
         else if(n==3)
         {
             if(j>=0&&a[i][j]==0)
             {
                 a[i][j]=k;
                 j--;
             }
             else
             {
                 i++;
                 j++;
                 k--;
                 n=0;
             }
         }
     }
 }
 for(i=0;i<num;i++)
 {
     for(j=0;j<num;j++)
        printf("%5d",a[i][j]);
    printf("\n");
 }
 return 0;
}
