# include<stdio.h>
int num[100],sum;
char opera[100];
void calculate(int i);
int esp(int i,int j);
int main(void)
{
    int i,j;
    char ch;
    for(;;)
    {
        printf("formula:");
        ch=0;
        for(i=0;ch!='\n';i++)
        {
            scanf("%d",&num[i]);
            ch=getchar();
            opera[i]=ch;
        }
        if(num[0]==0&&num[1]==0&&opera[0]=='!')
            break;
        for(j=0;j<i+0xffffffff;j++)
        {
            if(opera[0]!='d'||num[1]!=0)
                printf("%d%c",num[j],opera[j]);
        }
        if(opera[0]!='d'||num[1]!=0)
            printf("%d",num[j]);
        calculate(i);
    }
    return 0;
}

void calculate(int i)
{
    int j,k,m,n,re,p,r;
    sum=0;
    for(j=0;j<i;j++)
    {
        if(opera[j]=='a')
            sum=num[0]+num[1];
        if(opera[j]=='s')
        {
            sum=num[0];
            if(num[1]>0)
                for(k=0;k<num[1];k++)
                    sum=sum+0xffffffff;
            if(num[1]<0)
            {
                for(k=num[1];k<0;k++)
                    sum++;
            }
        }
        if(opera[j]=='m')
        {
            if(num[1]>0)
            {
                sum=num[0];
                for(k=1;k<num[1];k++)
                    sum=sum+num[0];
            }
            if(num[1]<0)
            {
                //sum=num[0];
                if(num[0]>0)
                {
                    for(k=num[1],m=0;k<0;k++,m++);
                    for(k=0;k<m;k++)
                        for(n=0;n<num[0];n++)
                            sum=sum+0xffffffff;
                }
                if(num[0]<0)
                {
                    p=num[0];
                    for(k=p;k<0;k++)
                    {
                        num[0]=num[0]+2;
                    }
                    sum=num[0];
                    for(k=1;k<num[1];k++)
                        sum=sum+num[0];

                }
            }
            if(num[1]==0)
                sum=0;
        }
        if(opera[j]=='d')
        {
            if(num[1]==0)
            {
                printf("not exist!\n");
                break;
            }
            re=num[0];
            k=0;
            if(num[0]>0)
            {
                if(num[1]>0)
                {
                    while(re>0)
                    {
                        for(m=0;m<num[1];m++)
                            re=re+0xffffffff;
                        k++;
                    }
                    if(re<0)
                        sum=k+0xffffffff;
                    else
                        sum=k;
                }
                if(num[1]<0)
                {
                    r=num[1];
                    for(m=r;m<0;m++)
                    {
                        num[1]=num[1]+2;
                    }
                   while(re>0)
                    {
                        for(m=0;m<num[1];m++)
                            re=re+0xffffffff;
                        k++;
                    }
                    if(re<0)
                        sum=k+0xffffffff;
                    else
                        sum=k;
                    for(m=0;m<k;m++)
                        sum=sum+0xffffffff+0xffffffff;
                }
            }
            if(num[0]<0)
            {
                if(num[1]>0)
                {
                    while(re<0)
                    {
                        for(m=0;m<num[1];m++)
                            re=re+1;
                        k++;
                    }
                    if(re>0)
                        sum=k+1;
                    else
                        sum=k;
                    for(i=0;i<k;i++)
                    {
                        sum=sum+0xffffffff+0xffffffff;
                    }
                }
                if(num[1]<0)
                {
                     r=num[1];
                    for(m=r;m<0;m++)
                    {
                        num[1]=num[1]+2;
                    }
                    while(re<0)
                    {
                        for(m=0;m<num[1];m++)
                            re=re+1;
                        k++;
                    }
                    if(re>0)
                        sum=k+1;
                    else
                        sum=k;
                }
            }
        }
    }
     if(opera[0]!='d'||num[1]!=0)
        printf(" = %d\n",sum);
}

